[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_variable = [
"tripy/__init__.py:__version__",
"setup.py:__version__"
]
hvcs = "gitlab"
major_on_zero = false
